// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsz9o1vKSlIY3UD50cagru5_0Pp9mMuQ',
    appId: '1:484613874252:web:eff655efdac2ce82fecae9',
    messagingSenderId: '484613874252',
    projectId: 'checking-otp-7c3fb',
    authDomain: 'checking-otp-7c3fb.firebaseapp.com',
    storageBucket: 'checking-otp-7c3fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRbtMNpZxpzooWVG74RlaM6fFHyABku5I',
    appId: '1:484613874252:android:0d8500ad5b5e4dcefecae9',
    messagingSenderId: '484613874252',
    projectId: 'checking-otp-7c3fb',
    storageBucket: 'checking-otp-7c3fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGhzXjAeGX87lqXm4A3Fcb2OU1Nojrg4',
    appId: '1:484613874252:ios:6838e925fc3ebc9cfecae9',
    messagingSenderId: '484613874252',
    projectId: 'checking-otp-7c3fb',
    storageBucket: 'checking-otp-7c3fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGhzXjAeGX87lqXm4A3Fcb2OU1Nojrg4',
    appId: '1:484613874252:ios:89af6fbb68934299fecae9',
    messagingSenderId: '484613874252',
    projectId: 'checking-otp-7c3fb',
    storageBucket: 'checking-otp-7c3fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
